git submodule add https://github.com/sjl/badwolf ./bundle/badwolf
git submodule add https://github.com/Raimondi/delimitMate.git ./bundle/delimitMate
git submodule add https://github.com/jondkinney/dragvisuals.vim.git ./bundle/dragvisuals
git submodule add https://github.com/morhetz/gruvbox.git ./bundle/gruvbox
git submodule add https://github.com/sjl/gundo.vim.git ./bundle/gundo
git submodule add https://github.com/davidhalter/jedi-vim.git ./bundle/jedi-vim
git submodule add https://github.com/tmhedberg/matchit.git ./bundle/matchit
git submodule add https://github.com/Shougo/neomru.vim.git ./bundle/neomru
git submodule add https://github.com/Shougo/neoyank.vim.git ./bundle/neoyank
git submodule add https://github.com/scrooloose/nerdtree.git ./bundle/nerdtree
git submodule add https://github.com/rust-lang/rust.vim.git ./bundle/rust
git submodule add https://github.com/scrooloose/syntastic.git ./bundle/syntastic
git submodule add https://github.com/SirVer/ultisnips.git ./bundle/ultisnips
git submodule add https://github.com/Shougo/unite-session.git ./bundle/unite
git submodule add https://github.com/Shougo/unite.vim.git ./bundle/unite-session
git submodule add https://github.com/vim-airline/vim-airline.git ./bundle/airline
git submodule add https://github.com/vim-airline/vim-airline-themes.git ./bundle/airline-themes
git submodule add https://github.com/altercation/vim-colors-solarized.git ./bundle/solarized
git submodule add https://github.com/zefei/vim-colortuner.git ./bundle/colortuner
git submodule add https://github.com/tpope/vim-commentary.git ./bundle/commentary
git submodule add https://github.com/easymotion/vim-easymotion.git ./bundle/easymotion
git submodule add https://github.com/tpope/vim-fugitive.git ./bundle/fugitive
git submodule add https://github.com/airblade/vim-gitgutter.git ./bundle/gitgutter
git submodule add https://github.com/michaeljsmith/vim-indent-object.git ./bundle/indent-object
git submodule add git://github.com/jeffkreeftmeijer/vim-numbertoggle.git ./bundle/numbertoggle
git submodule add https://github.com/sickill/vim-pasta.git ./bundle/pasta
git submodule add https://github.com/tpope/vim-pathogen.git ./bundle/pathogen
git submodule add git://github.com/tpope/vim-repeat.git ./bundle/repeat
git submodule add https://github.com/justinmk/vim-sneak.git ./bundle/sneak
git submodule add https://github.com/mhinz/vim-startify.git ./bundle/startify
git submodule add git://github.com/tpope/vim-surround.git ./bundle/surround
git submodule add https://github.com/bronson/vim-trailing-whitespace.git ./bundle/trailing-whitespace
git submodule add https://github.com/Shougo/vimproc.vim.git ./bundle/vimproc
git submodule add https://github.com/Shougo/vimshell.vim.git ./bundle/vimshell

